# Generated by Django 2.2.5 on 2020-09-06 04:46

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200607_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
