# Generated by Django 2.2.5 on 2021-04-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20210412_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='contact_number',
        ),
    ]
