version: '3'

services: 
    postgres-db:
        image: postgres:9.6
        container_name: postgres-db
        ports: 
            - "1234:5432"
        environment:
            - POSTGRES_DB=dreamhome
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres123
        networks: 
            main:
                aliases: 
                    - postgres-db
        tty: true
        stdin_open: true
    django-server:
        # build: .
        image: djangoserver:1.3-debian
        container_name: django-server
        ports: 
            - "8008:8000"
        volumes: 
            - .:/dreamhome
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        depends_on: 
            - postgres-db
        networks: 
            main:
                aliases: 
                    - django-server
        tty: true
        stdin_open: true
networks: 
    main: