version: '3'

services: 
    postgres-db:
        image: postgres:9.6
        container_name: postgres-db
        ports: 
            - "1234:5432"
        environment:
            - POSTGRES_DB=dreamhome
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres123
        volumes:
            - ~/dreamhome/postgres-data:/var/lib/postgresql/data
        networks: 
            main:
                aliases: 
                    - postgres-db
        tty: true
        stdin_open: true
    django-server:
        # build: .
        image: koavan/djangoserver:version-1.0
        container_name: django-server
        volumes:
            - .:/src
        working_dir: /src
        depends_on:
            - postgres-db
        command: sh -c "sleep 20 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        # command: sh -c "sleep 20 && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8008:8000"
        networks:
            main:
                aliases:
                    - django-server
        tty: true
        stdin_open: true
networks: 
    main: