# Generated by Django 2.2.5 on 2020-07-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proprepo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='profiles.Owner'),
        ),
    ]
