# Generated by Django 2.2.5 on 2020-07-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proprepo', '0002_auto_20200702_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Owner'),
        ),
    ]
