# Generated by Django 2.2.5 on 2021-01-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprepo', '0003_auto_20200702_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='is_layout',
            field=models.BooleanField(default=False),
        ),
    ]
